### ISSUE TITLE
Value width tracking

### ISSUE THREAD

**Issue by Amanieu** [bnjbvr/regalloc.rs#14]
On many architectures (e.g x86 and ARM64), `f32` and `f64` values are located in the `V128` register class. This means that any spills or moves will need to copy the entire 128 bits of the register.

However (on ARM64 at least) 128-bit load/store/move instructions are split into 2 uops, whereas 64-bit ones can be executed in a single uops. It would be beneficial to know whether the upper 64 bits of a `V128` are dead, in which case we can use a cheaper instruction for inserted spill/reload/move instructions.

**Comment by julian-seward1** [comment]
I would assume that the decision as to whether to split a 128-bit load/store/move into two uops is dependent on the particular processor implementation.  I can't imagine that high end implementations doing that.

But nevertheless .. interesting.  Do you happen to know whether there is any kind of ARM compiler-writer's guide, equivalent to Intel's "Optimization Reference Manual" ?

**Comment by Amanieu** [comment]
ARM sometimes publishes software optimization guides (Cortex [A72](https://static.docs.arm.com/uan0016/a/cortex_a72_software_optimization_guide_external.pdf), [A57](https://static.docs.arm.com/uan0015/b/Cortex_A57_Software_Optimization_Guide_external.pdf), [A55](https://static.docs.arm.com/epm128372/20/arm_cortex_a55_software_optimization_guide_v2.pdf)), but not all cores have them. Otherwise I usually find out the details of the CPU pipelines from Anandtech articles which go into quite a bit of detail.

It seems that the very latest cores (A77, A76) do have full 128-bit FP and load/store pipelines and won't suffer from us emitting 128-bit spill/reload/move instructions. However the 3 cores that have optimization guides all show that the FP pipelines and load/store units are only 64 bits.

Also I forgot to mention that an added benefit here is that we would only need to use one spill slot instead of two for `f64` values.

**Comment by cfallin** [comment]
It occurs to me that aside from the more complex, more traditional ways of doing this (overlapping register classes, tracking dead halves, ...), there might be a simple way to extend the current interface.

In particular, what if we passed the virtual register alongside other parameters when (i) querying the client how large a spillslot should be and (ii) generating spill, fill (and I suppose move) instructions? Basically, we provide a little extra semantic information: we're not just allocating a spillslot for a real register of this class, but a real register of this class *while storing this particular virtual register*. (If the regalloc wants to coalesce spillslots, it could take the max of the required sizes for each virtual register that occupies the slot at some point; a slot is still a slot, and it's not strongly typed or tied to the virtreg.)

This is sort of halfway to a type system (types on virtregs, real-reg spans, and spillslot spans), but doesn't require any additional definitions or infrastructure. For the initial client (Cranelift), it should be as simple as keeping a table from virtreg number back to Cranelift type (`F32` / `F64` / bona-fide `V128`). Thoughts?

**Comment by Amanieu** [comment]
That's a neat idea. You could also implement rematerialization for constants with this: if a vreg is known to have a constant value then you can no-op the spills and re-generate the constant for fills.

**Comment by bnjbvr** [comment]
Isn't rematerialization a regalloc concept, though? The choice to rematerialize should happen whenever considering a spill, and comparing the spilling cost vs the rematerialization cost, the former being only known to the regalloc.

**Comment by julian-seward1** [comment]
@bnjbvr, I think this is two separate questions.  I agree that management of the costs of rematerialization vs spilling is probably best left to the allocator.  However, there's still the question of knowing whether a vreg (or part of a vreg) contains a constant value and if so what it is.  And it's not obvious to me that the allocator can know that; it might be the client that has that information.

**Comment by julian-seward1** [comment]
"it's not obvious to me that the allocator can know that" -- actually this is wrong.  The allocator sees the entire vregisterised code, so obviously it could in principle do arbitrarily expensive analysis to determine constantness.  However, it may be that the client already has that information, and so asking it might be cheaper.

**Comment by bjorn3** [comment]
> However, it may be that the client already has that information, and so asking it might be cheaper.

Also the client might know that a memory location isn't changed between a load and the place where the loaded value is filled again.

**Comment by julian-seward1** [comment]
Also (to further contradict my earlier assertion) the allocator can't do any kind of constancy analysis given the current interface design, because the design assumes that instructions are opaque to the allocator, except for being able to ask about and change register uses.  So any information about constancy must come from the client.

**Comment by cfallin** [comment]
I created a PR just now that implements the vreg-parameter interface change; it seems that this addresses the immediate concern (allowing the client to use different-width spill/reload/move insns and spillslots), while the discussion about constant propagation, rematerialization and such could perhaps be split off into separate issues?

I'll hold off on merging the PR though in case anyone disagrees :-)

**Comment by julian-seward1** [comment]
@cfallin, sorry, I should have spoken earlier.  I think we should not make this change right now.   We don't need it for the MVP allocator, and when we come to implementing rematerialisation, our understanding of the problem, and hence our requirements for the interface, might have changed.  So I would say .. don't merge this at this point.

That said I do acknowledge that there's a bunch of useful design ideas in this thread.  We'll definitely want to come back to it.

**Comment by cfallin** [comment]
No worries, I'm happy to hold off if that's the decision. I do want to say though that I'm a little worried that spill-heavy floating point code, in particular, might suffer without this (on both arm64 and x86), with twice-as-large spills. To my mind, passing along the vreg seems like a low-risk change (unlikely that the regalloc would not have this information at hand easily; indeed this was the case in the PR), so perhaps it's reasonable to address the spill-width question this way for now? All the rest of the post-MVP features (remat, etc.) seem to me to be orthogonal anyway to the very simple, direct question of "which vreg am I loading with this reload?".

But, happy to go either way if you feel very strongly about it!

**Comment by julian-seward1** [comment]
I don't feel terribly strongly about it; if you want to land it I won't stand in the way [it's your decision!].  (As you know) I am in general a little wary about adding complexity before we know we need it, and I'd guess there are a bunch of other things we need as a higher priority than rematerialisation.  Also, in an ideal scenario we could drive the RA (and isel) tuning work by profiling the generated code and seeing what's bad.  We have machinery to find and print out the hottest blocks, so as to drive that along.

**Comment by cfallin** [comment]
Following discussion with Julian last week, I think I'm going to go ahead and merge this, as it does seem to be the simplest way to get appropriately-sized slot loads/stores and we'll want that for the MVP.

**Comment by cfallin** [comment]
Closed by #15. I'll create another issue for the rematerialization discussion above (which I agree should come much later, after the MVP).
