### ISSUE TITLE
Pass `&self` in `map_regs` in `Function`?

### ISSUE THREAD

**Issue by playXE** [bnjbvr/regalloc.rs#18]
This would be a nice thing if implementation of `Function` need to do some other work when this happens. In my VM for example I don't have register classes and all registers is just `u32` values, and when allocating register `regalloc.rs` may panic that some register from some instruction is not "real" and I had to use `statc mut` there:
```rust
    fn map_regs(
        insn: &mut Self::Inst,
        pre_map: &Map<VirtualReg, RealReg>,
        post_map: &Map<VirtualReg, RealReg>,
    ) {
        unsafe {
            MAPED = true;
        }
        insn.map_regs_d_u(
            /* define-map = */ post_map, /* use-map = */ pre_map,
        );
    }

    fn get_regs(&self, insn: &Self::Inst) -> regalloc::InstRegUses {
        let (d, m, u) = insn.get_reg_usage(unsafe { MAPED }); // if `MAPED` is true instead of creating virtual registers we create real register (`Reg::new_real`)

        regalloc::InstRegUses {
            used: u,
            defined: d,
            modified: m,
        }
    }
```

**Comment by cfallin** [comment]
Hi @playXE, the reason the interface is currently this way is that usually the `Function` implementer is some sort of container for instructions, and `map_regs` needs a mutable borrow for an instruction. This instruction borrow would conflict with an immutable borrow of the whole container. (We perhaps could have designed it to instead take an `Inst` owned, and return a new `Inst`, but that might be slightly more expensive than mutating in place.)

For your issue, it's not entirely clear to me what `MAPED` means, or why you're returning either virtual or real registers conditionally. The way the interface is intended to be used, we have register slots in instructions that can hold either virtual or real registers, they mostly start as virtual, and `map_regs` is guaranteed to be called to change all virtual regs to real regs. So you shouldn't need to do this mutation (or change what you return) yourself. In other words, just store a `Reg` for each register.

Hopefully that made sense! Perhaps I'm still not understanding your use-case though?

**Comment by playXE** [comment]
Thanks for your reply @cfallin ! I don't really need this thing in my bytecode now, every "real" register is <= 32 and registers bigger than 32 is now virtual register :)
