### ISSUE TITLE
When a reg is both used and modified, should it be in the mod/use set or both?

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/regalloc.rs#26]
When put in the `tests` directory, this test case triggers an assertion:

```
v1 = i32

b0:
    imm v1, 0
    addm v1, v1
    finish v1
```

```
thread 'main' panicked at 'assertion failed: !uce.map(|r| Writable::from_reg(*r)).intersects(&m0d)', bin/test_framework.rs:690:5
```

This is because for addm, v1 is both used (second operand) and modified (first operand). @julian-seward1 told me to open an issue so we can think about the proper solution.

Things we're considered:

- in the test framework, for all the modified instructions, mark src as used iff it's not equal to dst.
- in the analysis itself, just before finishing computing the instruction reg uses, the set of uses is computed as the previous set of uses minus the mod set: `uce = uce \ mod`.

**Comment by cfallin** [comment]
This is an interesting corner case! FWIW, the latter option (subtract all mods from use-set during regalloc's analysis) seems right to me; from the point of view of the client, the register *is* both a mod and use (as you say), and it is a subtle requirement to ask of the client to preprocess the sets in this way, IMHO.

**Comment by julian-seward1** [comment]
So, this is a bit of an interesting question.  I wanted to consider it in a
bit of depth primarily to convince myself that the core allocator designs are
correct.  In particular, the way in which they use a dual mapping scheme
(mapD, mapU) to apply their decision to each instruction.  Any design error in
that would be a serious problem in this stage in the game.

However, I think all is well.  The design is correct in this aspect, and the
only problem lies with test framework's `fn get_reg_usage`.  This violates the
allocator's stated API requirement that `intersect(def, mod) == empty_set` and
`intersect(use, mod) == empty_set`.  But then it *asserts* these invariants
and hence fails.

Both `fn get_reg_usage` for x64 and for arm64 actually handle this
properly.  They do that by post-processing the three sets, thusly:
```
    // Enforce invariants described above.
    iru.defined.remove(&iru.modified);
    iru.used.remove(&Set::from_vec(
        iru.modified.iter().map(|r| r.to_reg()).collect(),
    ));
```
and I suggest the test framework's `get_reg_usage` should be fixed the same way
by adding the above bit right at the end of it.

@bjnbvr writes

> in the analysis itself, just before finishing computing the instruction reg
> uses, the set of uses is computed as the previous set of uses minus the mod
> set: uce = uce \ mod.

Given that incorrect `get_regs` implementations can cause hard to find errors
in allocation, I'd prefer a different approach, in which we (the allocator)
are very picky about what we are told:

* for every place where we call get_regs (there are only 2, I think), assert
  for emptyness of the use/mod and def/mod intersections.  Maybe even a
  release assert.

That will force all clients to get this exactly right.  And will make it clear
when they are wrong.  Postprocessing the sets on the allocator side to enforce
the invariant by contrast could have the effect of hiding bugs in client
`get_reg`s.

**Comment by bnjbvr** [comment]
Well, I agree with @cfallin that this is a subtle requirement. Is the intent here just to defer the responsibility to the user, who may also blindly do the set-minus operation before handing over the sets, as done in both the WIP ARM64 and x64 implementations? Doing it there doesn't help figuring bugs related to this, and users may be likely to just paste this code their too. So, doing it on their behalf would provide users a better embedding experience with the same effect as if they did it on their code, thus I think this is what we should prefer doing.

**Comment by julian-seward1** [comment]
@bnjbvr "So, doing it on their behalf would provide users a better embedding experience with the same effect as if they did it on their code, thus I think this is what we should prefer doing."

Ok, yes, fair enough .. we also want to to provide a good embedding experience.  So let me change my story .. let's do it on the allocator side.  So I believe we are all agreed now.
