### ISSUE TITLE
Require that Function::Inst implements Debug?

### ISSUE THREAD

**Issue by bnjbvr** [bnjbvr/regalloc.rs#33]
It would certainly be nice for debugging, so as to be able to print instructions directly from regalloc.rs without having to print only the instruction numbers, and printing somewhere else the instructions themselves. It's probably not controversial, but wanted to see if anybody had good reasons not to do it.

**Comment by cfallin** [comment]
+1, sounds reasonable to me -- it's already true for our Cranelift  use case.
