### ISSUE TITLE
Possible fuzz-found error in the checker

### ISSUE THREAD

**Issue by julian-seward1** [bnjbvr/regalloc.rs#36]
The fuzzer constructed the following (almost comically ridiculous, but nevertheless valid) test case, which causes the checker to complain:
```
v26I = i32
b0:
   imm     v26I, 1499027801
   if_then_else v26I, b2:b2, b2:b2
b1:
   if_then_else v26I, b2:b2, b2:b2
b2:
   if_then_else v26I, b0:b0, b1:b1
```
BT simply assigns v26I consistently to r0, and I'd be surprised if LSRA didn't do the same.  This seems correct to me, but the checker complains with:
```
Checker error: UnknownValueInReg { real_reg: r0I, inst: i2 }
Checker error: UnknownValueInReg { real_reg: r0I, inst: i3 }
```
This is a bit of a nuisance, since it makes it impossible to use the fuzzer currently.  As of `4fe807a6` of about 24 hours ago, fuzzing now uses the checker by default.

You can reproduce the failure with the current tree (`7cafa314` or later) simply by running
```
RUST_LOG=debug cargo run -- -a btc -t fuzz_checker1 -f 8 -i 8
```
and `-a lsrac` fails identically.

**Comment by cfallin** [comment]
Fixed in `ab75e2139c2f49fe0c54492dfc21ea6bd23c45be` -- this was a very silly basic error in the dataflow loop (details in commit message). Thanks for finding it!
